import React from 'react';
import {
  BookOpenIcon,
  CodeBracketIcon,
  UserGroupIcon,
  LightBulbIcon,
  ShieldCheckIcon,
  RocketLaunchIcon
} from '@heroicons/react/24/outline';

const FeatureCard = ({ icon: Icon, title, description }) => (
  <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
    <div className="flex items-center space-x-3 mb-4">
      <div className="flex items-center justify-center w-10 h-10 bg-primary-100 rounded-lg">
        <Icon className="w-6 h-6 text-primary-600" />
      </div>
      <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
    </div>
    <p className="text-gray-600">{description}</p>
  </div>
);

const AboutPage = () => {
  const features = [
    {
      icon: BookOpenIcon,
      title: "Documentation Search",
      description: "Search through official Xinference documentation with semantic understanding to find exactly what you need."
    },
    {
      icon: CodeBracketIcon,
      title: "GitHub Integration",
      description: "Access real solutions from GitHub issues and source code to solve problems faced by the community."
    },
    {
      icon: LightBulbIcon,
      title: "AI-Powered Answers",
      description: "Get intelligent responses generated by AI that combines information from multiple sources for comprehensive answers."
    },
    {
      icon: UserGroupIcon,
      title: "Community Knowledge",
      description: "Benefit from the collective knowledge of the Xinference community through curated questions and answers."
    },
    {
      icon: ShieldCheckIcon,
      title: "Source Attribution",
      description: "Every answer includes clear source attribution so you can verify information and dive deeper when needed."
    },
    {
      icon: RocketLaunchIcon,
      title: "Fast & Reliable",
      description: "Get instant answers with confidence scores and response times, so you can trust the information you receive."
    }
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-12">
      {/* Hero Section */}
      <div className="text-center space-y-6">
        <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl">
          About Xinference Q&A Agent
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          An intelligent assistant designed to help you get the most out of Xinference, 
          the open-source platform for running AI model inference.
        </p>
      </div>

      {/* What is this section */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">What is this?</h2>
        <div className="prose prose-lg max-w-none text-gray-600">
          <p>
            The Xinference Q&A Agent is an AI-powered assistant that helps users find answers 
            to their questions about Xinference. Whether you're trying to install Xinference, 
            deploy models, troubleshoot issues, or understand advanced features, this agent 
            can provide instant, accurate answers.
          </p>
          <p>
            The agent searches through multiple sources including official documentation, 
            GitHub issues, and source code to provide comprehensive answers with proper 
            source attribution. Each response includes a confidence score and links to 
            the original sources for verification.
          </p>
        </div>
      </div>

      {/* Features Grid */}
      <div className="space-y-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Key Features</h2>
          <p className="text-lg text-gray-600">
            Powerful capabilities to help you succeed with Xinference
          </p>
        </div>
        
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>
      </div>

      {/* How it works */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">How it works</h2>
        <div className="grid gap-8 md:grid-cols-3">
          <div className="text-center">
            <div className="flex items-center justify-center w-12 h-12 bg-primary-100 rounded-full mx-auto mb-4">
              <span className="text-xl font-bold text-primary-600">1</span>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Ask Your Question</h3>
            <p className="text-gray-600">
              Type your question about Xinference in natural language. The system understands 
              context and can handle complex queries.
            </p>
          </div>
          
          <div className="text-center">
            <div className="flex items-center justify-center w-12 h-12 bg-primary-100 rounded-full mx-auto mb-4">
              <span className="text-xl font-bold text-primary-600">2</span>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Search & Analyze</h3>
            <p className="text-gray-600">
              The agent searches through documentation, GitHub issues, and source code using 
              semantic search to find the most relevant information.
            </p>
          </div>
          
          <div className="text-center">
            <div className="flex items-center justify-center w-12 h-12 bg-primary-100 rounded-full mx-auto mb-4">
              <span className="text-xl font-bold text-primary-600">3</span>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Get Your Answer</h3>
            <p className="text-gray-600">
              Receive a comprehensive answer with source attribution, confidence score, 
              and links to dive deeper into the topic.
            </p>
          </div>
        </div>
      </div>

      {/* Data Sources */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">Data Sources</h2>
        <div className="grid gap-6 md:grid-cols-3">
          <div className="text-center">
            <BookOpenIcon className="w-12 h-12 text-blue-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Official Documentation</h3>
            <p className="text-gray-600">
              Complete documentation from inference.readthedocs.io including installation guides, 
              API references, and tutorials.
            </p>
          </div>
          
          <div className="text-center">
            <UserGroupIcon className="w-12 h-12 text-green-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 mb-2">GitHub Issues</h3>
            <p className="text-gray-600">
              Real problems and solutions from the Xinference GitHub repository, including 
              bug reports, feature requests, and community discussions.
            </p>
          </div>
          
          <div className="text-center">
            <CodeBracketIcon className="w-12 h-12 text-purple-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Source Code</h3>
            <p className="text-gray-600">
              Direct access to the Xinference source code for implementation details 
              and advanced configuration options.
            </p>
          </div>
        </div>
      </div>

      {/* Links */}
      <div className="bg-gray-50 rounded-lg p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">Learn More About Xinference</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <a
            href="https://inference.readthedocs.io/"
            target="_blank"
            rel="noopener noreferrer"
            className="block p-4 bg-white rounded-lg border border-gray-200 hover:border-primary-300 hover:shadow-md transition-all"
          >
            <h3 className="font-semibold text-gray-900 mb-2">Documentation</h3>
            <p className="text-sm text-gray-600">Official documentation and guides</p>
          </a>
          
          <a
            href="https://github.com/xorbitsai/inference"
            target="_blank"
            rel="noopener noreferrer"
            className="block p-4 bg-white rounded-lg border border-gray-200 hover:border-primary-300 hover:shadow-md transition-all"
          >
            <h3 className="font-semibold text-gray-900 mb-2">GitHub Repository</h3>
            <p className="text-sm text-gray-600">Source code and issue tracker</p>
          </a>
          
          <a
            href="https://github.com/xorbitsai/inference/issues"
            target="_blank"
            rel="noopener noreferrer"
            className="block p-4 bg-white rounded-lg border border-gray-200 hover:border-primary-300 hover:shadow-md transition-all"
          >
            <h3 className="font-semibold text-gray-900 mb-2">Issues & Support</h3>
            <p className="text-sm text-gray-600">Community support and bug reports</p>
          </a>
          
          <a
            href="https://discord.gg/Xw9tszSkr5"
            target="_blank"
            rel="noopener noreferrer"
            className="block p-4 bg-white rounded-lg border border-gray-200 hover:border-primary-300 hover:shadow-md transition-all"
          >
            <h3 className="font-semibold text-gray-900 mb-2">Discord Community</h3>
            <p className="text-sm text-gray-600">Join the community chat</p>
          </a>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
